### PR TITLE
Next.js 11 Upgrade

### LINKED ISSUE #726: [Next.js 11] Type error: Argument of type 'PreviewData' is not assignable to parameter of type 'EditingPreviewData'. Type 'undefined' is not assignable to type 'EditingPreviewData'.
## Description

When upgrading a Sitecore JSS app from Next.js 10 to Next.js 11, the `jss build` command is failing with the following error:

```
./src/lib/page-props-factory.ts:87:60
Type error: Argument of type 'PreviewData' is not assignable to parameter of type 'EditingPreviewData'.
  Type 'undefined' is not assignable to type 'EditingPreviewData'.

  85 |        */
  86 |       // If we're in preview (editing) mode, use data already sent along with the editing request
> 87 |       const data = await editingDataService.getEditingData(context.previewData);
     |                                                            ^
  88 |       if (!data) {
  89 |         throw new Error(
  90 |           `Unable to get editing data for preview ${JSON.stringify(context.previewData)}`
info  - Checking validity of types .npm ERR! code ELIFECYCLE
```

This is caused by a type change in Next.js between versions 10 and 11. Specifically, `GetServerSidePropsContext.previewData` and `GetStaticPropsContext.previewData` types changed from `any` to `PreviewData`. `PreviewData` is declared as `string | false | object | undefined`. This new type does not match sitecore-jss-nextjs `EditingPreviewData` which is declared as:

```TypeScript
export interface EditingPreviewData {
    key: string;
    serverUrl: string;
}
```

## Expected behavior

I expect sitecore-jss-nextjs package types to be compatible with Next.js 11.

## Steps To Reproduce

1. Upgrade a JSS Next.js application to Next.js 11.
2. Run the `jss build` command.

## Possible Fix

As a workaround for now, I added a `EditingPreviewData` type cast to the line causing the error.

Before:

```TypeScript
const data = await editingDataService.getEditingData(context.previewData);
```

After:

```TypeScript
const data = await editingDataService.getEditingData(context.previewData as EditingPreviewData);
```

## Your Environment

* Sitecore Version: 10.1.0
* Next.js Version: 11.0.0
* React Version: 17.0.2
* JSS Version: 16.0.0 (Same problem occurs with version 18.0.0-canary.1)
* Operating System and version: Windows 10 v1909

### PR DESCRIPTION
**Pull request by ambrauer**
## Description / Motivation
Update to latest Next.js version 11.0.1.

- React updated to 17.0.2 (required for next 11.0.1)
- Accept Nextjs `PreviewData` (new type) for `getEditingData` parm
- ESLint upgrade / refresh to utilize [Next.js-provided config](https://nextjs.org/docs/basic-features/eslint)
- `useComponentProps` hook modified to handle undefined / key not found parameter. This allows us to avoid using the hook in a conditional (which is a bad practice and now being picked up by [Next's OOTB eslint rules](https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level))
- Fix other lint, TypeScript, compile issues
- Enable React Strict Mode (recommended)
- Remove [SSR notFound workaround](https://github.com/Sitecore/jss/pull/597) (now fixed in Nextjs) 
- Refresh custom _error component - make it clear this covers both server and client vs the custom 500 page which only covers server.
- E2E Cypress tests - removed commented out Nextjs config since `PORT` env variable is [now fully supported](https://nextjs.org/docs/upgrading#port-is-now-supported-for-next-dev-and-next-start)

Closes #726 

## Testing Details
Manually tested connected/disconnected/production/export/EE/Horizon locally. All Cypress tests passing.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update (non-breaking change; modified files are limited to the `/docs` directory)

### CODE REVIEW

File: samples/nextjs/src/Layout.tsx [hunk 1]
```diff
@@ -59,7 +59,7 @@ const Layout = ({ context }: LayoutProps): JSX.Element => {
   // Note the context object type here matches the initial value in [[...path]].tsx.
   useEffect(() => {
     updateSitecoreContext && updateSitecoreContext(context);
-  }, [context]);
+  }, [updateSitecoreContext, context]);
```
Comment (illiakovalenko) [inline samples/nextjs/src/Layout.tsx:62]: What is the reason to add `updateSitecoreContext` here?

File: samples/nextjs/src/lib/page-props-factory.ts [hunk 2]
```diff
@@ -12,7 +12,7 @@ import { SitecorePageProps } from 'lib/page-props';
 import { dictionaryServiceFactory } from 'lib/dictionary-service-factory';
 import { layoutServiceFactory } from 'lib/layout-service-factory';
 import { componentModule } from 'temp/componentFactory';
-import { config as packageConfig } from '../../package.json';
+import pkg from '../../package.json';
```
Comment (illiakovalenko) [inline samples/nextjs/src/lib/page-props-factory.ts:15]: I'm wondering, was some typescript error here?

File: samples/nextjs/src/pages/_error.tsx [hunk 3]
```diff
@@ -6,17 +6,20 @@ interface ErrorPageProps {
 }
```
Comment (illiakovalenko) [inline samples/nextjs/src/pages/_error.tsx:6]: I see your comment in description:
'Refresh custom _error component - make it clear this covers both server and client vs the custom 500 page which only covers server.'
But previously it handled both client and server side errors, as I see. What was changed?

**Review by illiakovalenko — CHANGES_REQUESTED** [review]
Looks great! See few questions below

File: samples/nextjs/src/Layout.tsx (hunk 1 above)
Comment (ambrauer) [reply samples/nextjs/src/Layout.tsx:62]: This was to satisfy the ['exhaustive-deps' lint rule](https://github.com/facebook/react/issues/14920). e.g. "React Hook useEffect has a missing dependency: 'updateSitecoreContext'. Either include it or remove the dependency array."

`react-hooks` ESLint plugin was brought in as part of [`eslint-config-next`](https://github.com/vercel/next.js/blob/canary/packages/eslint-config-next/index.js).

File: samples/nextjs/src/pages/_error.tsx (hunk 3 above)
Comment (ambrauer) [reply samples/nextjs/src/pages/_error.tsx:6]: Nothing really changed with [_error.tsx](https://nextjs.org/docs/advanced-features/custom-error-page#more-advanced-error-page-customizing) (correct, always handled both server and client). What changed is that Next has since also introduced the option to add a [custom 500 page](https://nextjs.org/docs/advanced-features/custom-error-page#customizing-the-500-page) (500.tsx), but this only handles server errors. I wanted to make it clear that our sample uses the more advanced option.

File: samples/nextjs/src/lib/page-props-factory.ts (hunk 2 above)
Comment (ambrauer) [reply samples/nextjs/src/lib/page-props-factory.ts:15]: Correct, these were causing typescript warnings.
```
./src/lib/page-props-factory.ts
Should not import the named export 'config'.'language' (imported as 'packageConfig') from default-exporting module (only default export is available soon)
```

**Review by illiakovalenko — APPROVED** [review]
Good job! Approved
