### PR TITLE
[Next.js] Next Link props unavailable when using Sitecore Link component

### LINKED ISSUE #2155: Next Link props unavailable when using Sitecore Link component
### Describe the Bug

Given JSS uses a Next/Link component for internal matching URLs, it should also make available all [the props of the Next/Link](https://nextjs.org/docs/pages/api-reference/components/link) component. e.g. `replace`, `shallow`, `as`.

It appears that newer versions introduced the `prefetch` prop, but stopped there. The current JSS Link is typed as ReactLink only (plus the prefetch prop)

### To Reproduce

Use the Link component in combination with the `replace` prop.

### Expected Behavior

Next/Link props work as expected when a Next/Link is rendered.

### Possible Fix

Add support for more Next/Link props similar to the `prefetch` prop that was added in newer versions.

### Provide environment information

* Sitecore Version: n/a
* JSS Version: ^22.9
* Browser Name and version: n/a
* Operating System and version (desktop or mobile): n/a
* Link to your project (if available): n/a

### PR DESCRIPTION
**Pull request by sc-nikolaoslazaridis**
- [x] This PR follows the [Contribution Guide](https://github.com/Sitecore/jss/blob/dev/CONTRIBUTING.md)
- [x] Changelog updated
- [ ] Upgrade guide entry added

## Description / Motivation
- Added missing NextLink props to Link component

Fixes #2155 

## Testing Details

- [x] Unit Test Added
- [ ] Manual Test/Other (Please elaborate)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by illiakovalenko — APPROVED** [review]

File: packages/sitecore-jss-nextjs/src/components/Link.tsx [hunk 1]
```diff
@@ -103,3 +111,28 @@ export const Link = forwardRef<HTMLAnchorElement, LinkProps>(
...
+function sanitizeLinkProps(props: LinkProps) {
+  const nextLinkProps: (keyof NextLinkProps)[] = [
+    'as',
+    'onNavigate',
+    'passHref',
+    'prefetch',
+    'replace',
+    'scroll',
+    'shallow',
+  ];
```
Comment (illiakovalenko) [inline packages/sitecore-jss-nextjs/src/components/Link.tsx]: Can we remove this extra list, since it's already defined at the top?

**Review by illiakovalenko — CHANGES_REQUESTED** [review]

**Review by illiakovalenko — APPROVED** [review]

File: packages/sitecore-jss-nextjs/src/components/Link.tsx (hunk 1 above)
Comment (illiakovalenko) [reply packages/sitecore-jss-nextjs/src/components/Link.tsx]: @sc-nikolaoslazaridis Please do the same for the Content SDK repository as well and create a new PR. That was part of my initial request.
